//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.WorkerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkerService.IWorkerService")]
    public interface IWorkerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/GetData", ReplyAction="http://tempuri.org/IWorkerService/GetDataResponse")]
        Entities.Response GetData(Entities.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/GetData", ReplyAction="http://tempuri.org/IWorkerService/GetDataResponse")]
        System.Threading.Tasks.Task<Entities.Response> GetDataAsync(Entities.Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkerServiceChannel : WinClient.WorkerService.IWorkerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkerServiceClient : System.ServiceModel.ClientBase<WinClient.WorkerService.IWorkerService>, WinClient.WorkerService.IWorkerService {
        
        public WorkerServiceClient() {
        }
        
        public WorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Response GetData(Entities.Request request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<Entities.Response> GetDataAsync(Entities.Request request) {
            return base.Channel.GetDataAsync(request);
        }
    }
}
